# Generated by Django 5.2.8 on 2025-11-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='description',
        ),
        migrations.AlterField(
            model_name='pitch',
            name='images',
            field=models.JSONField(blank=True, help_text='List of image URLs for the pitch', null=True),
        ),
    ]
