# Generated by Django 5.2.8 on 2025-11-22 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_pitch_address_remove_pitch_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_slot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['time_slot__start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pitch', 'booking_date', 'start_time', 'end_time'], name='main_bookin_pitch_i_f73425_idx'),
        ),
        migrations.AddField(
            model_name='pitchtimeslot',
            name='pitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='main.pitch'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='pitchtimeslot',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_slots', to='main.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='pitchtimeslot',
            unique_together={('pitch', 'time_slot')},
        ),
    ]
