# Generated by Django 5.2.8 on 2025-11-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pitchtimeslot_timeslot_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='main_bookin_pitch_i_f73425_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='pitchtimeslot',
            name='price_per_slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.pitchtimeslot'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pitch', 'booking_date', 'time_slot'], name='main_bookin_pitch_i_0bd4f1_idx'),
        ),
    ]
